// <auto-generated />
using Froggies.Web.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Froggies.Web.DB.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190625185217_FirstLevel")]
    partial class FirstLevel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Froggies.Web.Model.Levels.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CellsJson")
                        .IsRequired()
                        .HasColumnName("Cells");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CellsJson = "[[\"G\",\"N\",\"E\",\"N\",\"E\"],[\"N\",\"G\",\"N\",\"E\",\"N\"],[\"E\",\"N\",\"G\",\"N\",\"E\"],[\"N\",\"R\",\"N\",\"E\",\"N\"],[\"E\",\"N\",\"E\",\"N\",\"E\"]]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
